### PR TITLE
(Display `Added:` date for new machines in LocationDetails view

### LINKED ISSUE #545: Newly added machines appear less prominent than they should
Because newly added machines ([`machine.created_at != machine.updated_at`](https://github.com/pinballmap/pbm-react/blob/b556e089213f6fc3662c6cfc4eca51685b42188a/app/screens/LocationDetails.js#L756C32-L756C72)) lack the `Updated: ` text line, they appear oddly "buried" or low-priority within Location Details list view.

Working on a PR now would should display `Added: ` for new machines, which don't yet have updates. This should make all machines the same height, _and_ make it easier to spot newly added machines (typically something I'm eager to discover!).
IMG_1441
IMG_1443

### PR DESCRIPTION
**Pull request by unitof**
Note that I have **not** tested or build this at all! Just working blind in the code here.

I'm a mostly a web developer but eager to get up to speed locally building/testing if needed.

Let me know if this breaks anything as-is or requires any other changes/tests and I can start learning!

Fixes #545

### CODE REVIEW

**Comment by unitof** [comment]
(PS: Jacob Ford here from the Patreon)

**Comment by unitof** [comment]
Oh, do you think a different icon would be appropriate for newly added machines? (Any place I can see the available icons?)

**Comment by RyanTG** [comment]
Thanks! Will test it out. 

Icons are here: https://icons.expo.fyi/Index

Unsure if a new one is necessary in this case...

**Comment by unitof** [comment]
Yeah, all I can think of is an "earlier" clock time, but that might be too clever by 3 hours.

**Comment by RyanTG** [comment]
Good idea. I changed it to three. Three and four - I thought those two times looked best.

I had to put the condition outside of the view, because of some jsx rule.

Thanks!

**Pull request merged**
